analytics: {}
color:
  brandColors: []
  brandStrength: 0.971284
  lightness: 0.521959
  rhythmicContrast: 1
  saturation: 0.984797
cta: {}
layout_spectrum: 0.983108
name: WhollyOdd
opengraph: {}
purpose: []
typography_spectrum: 0.632601
