name: WhollyOdd
favicon: null
layout_spectrum: 0.98793
typography_spectrum: 0.62658
title: My Internet Brain Dump
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.971284
  lightness: 0.521959
  saturation: 0.984797
  rhythmicContrast: 1
purpose: []
